spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sso?allowPublicKeyRetrieval=true&useSSL=false
    username: YourUsername
    password: YourPassword
    driver-class-name: com.mysql.cj.jdbc.Driver
jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
